//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
<<<<<<< HEAD
//     Runtime Version:4.0.30319.18408
=======
//     Runtime Version:4.0.30319.18063
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socioboard.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/DropboxAccount.asmx")]
        public string Socioboard_Api_DropboxAccount_DropboxAccount {
            get {
                return ((string)(this["Socioboard_Api_DropboxAccount_DropboxAccount"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.socioboard.com/Services/TwitterAccount.asmx")]
        public string Socioboard_Api_TwitterAccount_TwitterAccountRepository1 {
            get {
                return ((string)(this["Socioboard_Api_TwitterAccount_TwitterAccountRepository1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/MailSender.asmx")]
        public string Socioboard_Api_MailSender_MailSender {
            get {
                return ((string)(this["Socioboard_Api_MailSender_MailSender"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/Admin.asmx")]
        public string Socioboard_Api_Admin_Admin {
            get {
                return ((string)(this["Socioboard_Api_Admin_Admin"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/AdminNews.asmx")]
        public string Socioboard_Api_AdminNews_AdminNews {
            get {
                return ((string)(this["Socioboard_Api_AdminNews_AdminNews"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/AdminPackageDetails.asmx")]
        public string Socioboard_Api_AdminPackageDetails_AdminPackageDetails {
            get {
                return ((string)(this["Socioboard_Api_AdminPackageDetails_AdminPackageDetails"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/AdminUserDetails.asmx")]
        public string Socioboard_Api_AdminUserDetails_AdminUserDetails {
            get {
                return ((string)(this["Socioboard_Api_AdminUserDetails_AdminUserDetails"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/Ads.asmx")]
        public string Socioboard_Api_Ads_Ads {
            get {
                return ((string)(this["Socioboard_Api_Ads_Ads"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/ArchiveMessage.asmx")]
        public string Socioboard_Api_ArchiveMessage_ArchiveMessage {
            get {
                return ((string)(this["Socioboard_Api_ArchiveMessage_ArchiveMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/BusinessSetting.asmx")]
        public string Socioboard_Api_BusinessSetting_BusinessSetting {
            get {
                return ((string)(this["Socioboard_Api_BusinessSetting_BusinessSetting"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/CompanyDashboard.asmx")]
        public string Socioboard_Api_CompanyDashboard_CompanyDashboard {
            get {
                return ((string)(this["Socioboard_Api_CompanyDashboard_CompanyDashboard"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/Companypage.asmx")]
        public string Socioboard_Api_Companypage_Companypage {
            get {
                return ((string)(this["Socioboard_Api_Companypage_Companypage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/Coupon.asmx")]
        public string Socioboard_Api_Coupon_Coupon {
            get {
                return ((string)(this["Socioboard_Api_Coupon_Coupon"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/DiscoverySearch.asmx")]
        public string Socioboard_Api_DiscoverySearch_DiscoverySearch {
            get {
                return ((string)(this["Socioboard_Api_DiscoverySearch_DiscoverySearch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/Drafts.asmx")]
        public string Socioboard_Api_Drafts_Drafts {
            get {
                return ((string)(this["Socioboard_Api_Drafts_Drafts"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/Dropbox.asmx")]
        public string Socioboard_Api_Dropbox_Dropbox {
            get {
                return ((string)(this["Socioboard_Api_Dropbox_Dropbox"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/Facebook.asmx")]
        public string Socioboard_Api_Facebook_Facebook {
            get {
                return ((string)(this["Socioboard_Api_Facebook_Facebook"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/FacebookAccount.asmx")]
        public string Socioboard_Api_FacebookAccount_FacebookAccount {
            get {
                return ((string)(this["Socioboard_Api_FacebookAccount_FacebookAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/FacebookFeed.asmx")]
        public string Socioboard_Api_FacebookFeed_FacebookFeed {
            get {
                return ((string)(this["Socioboard_Api_FacebookFeed_FacebookFeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/FbPageComment.asmx")]
        public string Socioboard_Api_FbPageComment_FbPageComment {
            get {
                return ((string)(this["Socioboard_Api_FbPageComment_FbPageComment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/TeamMemberProfile.asmx")]
        public string Socioboard_Api_TeamMemberProfile_TeamMemberProfile {
            get {
                return ((string)(this["Socioboard_Api_TeamMemberProfile_TeamMemberProfile"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/FbPageLiker.asmx")]
        public string Socioboard_Api_FbPageLiker_FbPageLiker {
            get {
                return ((string)(this["Socioboard_Api_FbPageLiker_FbPageLiker"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/TwitterAccount.asmx")]
        public string Socioboard_Api_TwitterAccount_TwitterAccount {
            get {
                return ((string)(this["Socioboard_Api_TwitterAccount_TwitterAccount"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/FbPagePost.asmx")]
        public string Socioboard_Api_FbPagePost_FbPagePost {
            get {
                return ((string)(this["Socioboard_Api_FbPagePost_FbPagePost"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/InstagramComment.asmx")]
        public string Socioboard_Api_InstagramComment_InstagramComment {
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/GooglePlusAccount.asmx")]
        public string Socioboard_Api_GooglePlusAccount_GooglePlusAccount {
            get {
                return ((string)(this["Socioboard_Api_GooglePlusAccount_GooglePlusAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/GroupProfile.asmx")]
        public string Socioboard_Api_GroupProfile_GroupProfile {
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            get {
                return ((string)(this["Socioboard_Api_InstagramComment_InstagramComment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/DiscoverySearch.asmx")]
        public string Socioboard_Api_DiscoverySearch_DiscoverySearch {
            get {
                return ((string)(this["Socioboard_Api_DiscoverySearch_DiscoverySearch"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/Groups.asmx")]
        public string Socioboard_Api_Groups_Groups {
            get {
                return ((string)(this["Socioboard_Api_Groups_Groups"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/LinkedinCompanyPage.asmx")]
        public string Socioboard_Api_LinkedinCompanyPage_LinkedinCompanyPage {
            get {
                return ((string)(this["Socioboard_Api_LinkedinCompanyPage_LinkedinCompanyPage"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/GroupScheduleMessage.asmx")]
        public string Socioboard_Api_GroupScheduleMessage_GroupScheduleMessage {
            get {
                return ((string)(this["Socioboard_Api_GroupScheduleMessage_GroupScheduleMessage"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/Dropbox.asmx")]
        public string Socioboard_Api_Dropbox_Dropbox {
            get {
                return ((string)(this["Socioboard_Api_Dropbox_Dropbox"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/Instagram.asmx")]
        public string Socioboard_Api_Instagram_Instagram {
            get {
                return ((string)(this["Socioboard_Api_Instagram_Instagram"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/InstagramAccount.asmx")]
        public string Socioboard_Api_InstagramAccount_InstagramAccount {
            get {
                return ((string)(this["Socioboard_Api_InstagramAccount_InstagramAccount"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/TwitterMessage.asmx")]
        public string Socioboard_Api_TwitterMessage_TwitterMessage {
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/InstagramComment.asmx")]
        public string Socioboard_Api_InstagramComment_InstagramComment {
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            get {
                return ((string)(this["Socioboard_Api_TwitterMessage_TwitterMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/PaymentTransaction.asmx")]
        public string Socioboard_Api_PaymentTransaction_PaymentTransaction {
            get {
                return ((string)(this["Socioboard_Api_PaymentTransaction_PaymentTransaction"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/InstagramFeed.asmx")]
        public string Socioboard_Api_InstagramFeed_InstagramFeed {
            get {
                return ((string)(this["Socioboard_Api_InstagramFeed_InstagramFeed"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/ArchiveMessage.asmx")]
        public string Socioboard_Api_ArchiveMessage_ArchiveMessage {
            get {
                return ((string)(this["Socioboard_Api_ArchiveMessage_ArchiveMessage"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/Linkedin.asmx")]
        public string Socioboard_Api_Linkedin_Linkedin {
            get {
                return ((string)(this["Socioboard_Api_Linkedin_Linkedin"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/User.asmx")]
        public string Socioboard_Api_User_User {
            get {
                return ((string)(this["Socioboard_Api_User_User"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/LinkedinAccount.asmx")]
        public string Socioboard_Api_LinkedinAccount_LinkedinAccount {
            get {
                return ((string)(this["Socioboard_Api_LinkedinAccount_LinkedinAccount"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/Team.asmx")]
        public string Socioboard_Api_Team_Team {
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/LinkedinCompanyPage.asmx")]
        public string Socioboard_Api_LinkedinCompanyPage_LinkedinCompanyPage {
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            get {
                return ((string)(this["Socioboard_Api_Team_Team"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/Twitter.asmx")]
        public string Socioboard_Api_Twitter_Twitter {
            get {
                return ((string)(this["Socioboard_Api_Twitter_Twitter"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/LinkedInFeed.asmx")]
        public string Socioboard_Api_LinkedInFeed_LinkedInFeed {
            get {
                return ((string)(this["Socioboard_Api_LinkedInFeed_LinkedInFeed"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/TicketAssigneeStatus.asmx")]
        public string Socioboard_Api_TicketAssigneeStatus_TicketAssigneeStatus {
            get {
                return ((string)(this["Socioboard_Api_TicketAssigneeStatus_TicketAssigneeStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/TwitterFeed.asmx")]
        public string Socioboard_Api_TwitterFeed_TwitterFeed {
            get {
                return ((string)(this["Socioboard_Api_TwitterFeed_TwitterFeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/MailSender.asmx")]
        public string Socioboard_Api_MailSender_MailSender {
            get {
                return ((string)(this["Socioboard_Api_MailSender_MailSender"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/Invitation.asmx")]
        public string Socioboard_Api_Invitation_Invitation {
            get {
                return ((string)(this["Socioboard_Api_Invitation_Invitation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/Admin.asmx")]
        public string Socioboard_Api_Admin1_Admin {
            get {
                return ((string)(this["Socioboard_Api_Admin1_Admin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/AdminNews.asmx")]
        public string Socioboard_Api_AdminNews_AdminNews {
            get {
                return ((string)(this["Socioboard_Api_AdminNews_AdminNews"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/AdminPackageDetails.asmx")]
        public string Socioboard_Api_AdminPackageDetails_AdminPackageDetails {
            get {
                return ((string)(this["Socioboard_Api_AdminPackageDetails_AdminPackageDetails"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/AdminUserDetails.asmx")]
        public string Socioboard_Api_AdminUserDetails_AdminUserDetails {
            get {
                return ((string)(this["Socioboard_Api_AdminUserDetails_AdminUserDetails"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/Ads.asmx")]
        public string Socioboard_Api_Ads_Ads {
            get {
                return ((string)(this["Socioboard_Api_Ads_Ads"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/Affiliates.asmx")]
        public string Socioboard_Api_Affiliates_Affiliates {
            get {
                return ((string)(this["Socioboard_Api_Affiliates_Affiliates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/Coupon.asmx")]
        public string Socioboard_Api_Coupon_Coupon {
            get {
                return ((string)(this["Socioboard_Api_Coupon_Coupon"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/NewsLetter.asmx")]
        public string Socioboard_Api_NewsLetter_NewsLetter {
            get {
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/NewsLetter.asmx")]
        public string Socioboard_Api_NewsLetter_NewsLetter {
            get {
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
                return ((string)(this["Socioboard_Api_NewsLetter_NewsLetter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/GroupProfile.asmx")]
        public string Socioboard_Api_GroupProfile_GroupProfile {
            get {
                return ((string)(this["Socioboard_Api_GroupProfile_GroupProfile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/FbPageLiker.asmx")]
        public string Socioboard_Api_FbPageLiker_FbPageLiker {
            get {
                return ((string)(this["Socioboard_Api_FbPageLiker_FbPageLiker"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/FbPageComment.asmx")]
        public string Socioboard_Api_FbPageComment_FbPageComment {
            get {
                return ((string)(this["Socioboard_Api_FbPageComment_FbPageComment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/FacebookAccount.asmx")]
        public string Socioboard_Api_FacebookAccount_FacebookAccount {
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/Package.asmx")]
        public string Socioboard_Api_Package_Package {
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            get {
                return ((string)(this["Socioboard_Api_Package_Package"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/PaymentTransaction.asmx")]
        public string Socioboard_Api_PaymentTransaction_PaymentTransaction {
            get {
                return ((string)(this["Socioboard_Api_PaymentTransaction_PaymentTransaction"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/ScheduledMessage.asmx")]
        public string Socioboard_Api_ScheduledMessage_ScheduledMessage {
            get {
                return ((string)(this["Socioboard_Api_ScheduledMessage_ScheduledMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/FacebookFeed.asmx")]
        public string Socioboard_Api_FacebookFeed_FacebookFeed {
            get {
                return ((string)(this["Socioboard_Api_FacebookFeed_FacebookFeed"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/SentimentalAnalysis.asmx")]
        public string Socioboard_Api_SentimentalAnalysis_SentimentalAnalysis {
            get {
                return ((string)(this["Socioboard_Api_SentimentalAnalysis_SentimentalAnalysis"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/GroupScheduleMessage.asmx")]
        public string Socioboard_Api_GroupScheduleMessage_GroupScheduleMessage {
            get {
                return ((string)(this["Socioboard_Api_GroupScheduleMessage_GroupScheduleMessage"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/SocialProfile.asmx")]
        public string Socioboard_Api_SocialProfile_SocialProfile {
            get {
                return ((string)(this["Socioboard_Api_SocialProfile_SocialProfile"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/FacebookMessage.asmx")]
        public string Socioboard_Api_FacebookMessage_FacebookMessage {
            get {
                return ((string)(this["Socioboard_Api_FacebookMessage_FacebookMessage"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/TaskComment.asmx")]
        public string Socioboard_Api_TaskComment_TaskComment {
            get {
                return ((string)(this["Socioboard_Api_TaskComment_TaskComment"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/GooglePlusAccount.asmx")]
        public string Socioboard_Api_GooglePlusAccount_GooglePlusAccount {
            get {
                return ((string)(this["Socioboard_Api_GooglePlusAccount_GooglePlusAccount"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/Tasks.asmx")]
        public string Socioboard_Api_Tasks_Tasks {
            get {
                return ((string)(this["Socioboard_Api_Tasks_Tasks"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/SocialProfile.asmx")]
        public string Socioboard_Api_SocialProfile_SocialProfile {
            get {
                return ((string)(this["Socioboard_Api_SocialProfile_SocialProfile"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/Team.asmx")]
        public string Socioboard_Api_Team_Team {
            get {
                return ((string)(this["Socioboard_Api_Team_Team"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/SentimentalAnalysis.asmx")]
        public string Socioboard_Api_SentimentalAnalysis_SentimentalAnalysis {
            get {
                return ((string)(this["Socioboard_Api_SentimentalAnalysis_SentimentalAnalysis"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/TeamMemberProfile.asmx")]
        public string Socioboard_Api_TeamMemberProfile_TeamMemberProfile {
            get {
                return ((string)(this["Socioboard_Api_TeamMemberProfile_TeamMemberProfile"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/Tasks.asmx")]
        public string Socioboard_Api_Tasks_Tasks {
            get {
                return ((string)(this["Socioboard_Api_Tasks_Tasks"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/TicketAssigneeStatus.asmx")]
        public string Socioboard_Api_TicketAssigneeStatus_TicketAssigneeStatus {
            get {
                return ((string)(this["Socioboard_Api_TicketAssigneeStatus_TicketAssigneeStatus"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/TaskComment.asmx")]
        public string Socioboard_Api_TaskComment_TaskComment {
            get {
                return ((string)(this["Socioboard_Api_TaskComment_TaskComment"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/Tumblr.asmx")]
        public string Socioboard_Api_Tumblr_Tumblr {
            get {
                return ((string)(this["Socioboard_Api_Tumblr_Tumblr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/TumblrAccount.asmx")]
        public string Socioboard_Api_TumblrAccount_TumblrAccount {
            get {
                return ((string)(this["Socioboard_Api_TumblrAccount_TumblrAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/TumblrFeed.asmx")]
        public string Socioboard_Api_TumblrFeed_TumblrFeed {
            get {
                return ((string)(this["Socioboard_Api_TumblrFeed_TumblrFeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/Twitter.asmx")]
        public string Socioboard_Api_Twitter_Twitter {
            get {
                return ((string)(this["Socioboard_Api_Twitter_Twitter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/TwitterAccount.asmx")]
        public string Socioboard_Api_TwitterAccount_TwitterAccount {
            get {
                return ((string)(this["Socioboard_Api_TwitterAccount_TwitterAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/TwitterDirectMessages.asmx")]
        public string Socioboard_Api_TwitterDirectMessages_TwitterDirectMessages {
            get {
                return ((string)(this["Socioboard_Api_TwitterDirectMessages_TwitterDirectMessages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/TwitterMessage.asmx")]
        public string Socioboard_Api_TwitterMessage_TwitterMessage {
            get {
                return ((string)(this["Socioboard_Api_TwitterMessage_TwitterMessage"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/CompanyDashboard.asmx")]
        public string Socioboard_Api_CompanyDashboard_CompanyDashboard {
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/TwitterStats.asmx")]
        public string Socioboard_Api_TwitterStats_TwitterStats {
            get {
                return ((string)(this["Socioboard_Api_TwitterStats_TwitterStats"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/User.asmx")]
        public string Socioboard_Api_User_User {
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            get {
                return ((string)(this["Socioboard_Api_CompanyDashboard_CompanyDashboard"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/Companypage.asmx")]
        public string Socioboard_Api_Companypage_Companypage {
            get {
                return ((string)(this["Socioboard_Api_Companypage_Companypage"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/Youtube.asmx")]
        public string Socioboard_Api_Youtube_Youtube {
            get {
                return ((string)(this["Socioboard_Api_Youtube_Youtube"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/ScheduledMessage.asmx")]
        public string Socioboard_Api_ScheduledMessage_ScheduledMessage {
            get {
                return ((string)(this["Socioboard_Api_ScheduledMessage_ScheduledMessage"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/YoutubeAccount.asmx")]
        public string Socioboard_Api_YoutubeAccount_YoutubeAccount {
            get {
                return ((string)(this["Socioboard_Api_YoutubeAccount_YoutubeAccount"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/Facebook.asmx")]
        public string Socioboard_Api_Facebook_Facebook {
            get {
                return ((string)(this["Socioboard_Api_Facebook_Facebook"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/YoutubeChannel.asmx")]
        public string Socioboard_Api_YoutubeChannel_YoutubeChannel {
            get {
                return ((string)(this["Socioboard_Api_YoutubeChannel_YoutubeChannel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/DropboxAccount.asmx")]
        public string Socioboard_Api_DropboxAccount_DropboxAccount {
            get {
                return ((string)(this["Socioboard_Api_DropboxAccount_DropboxAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/FacebookMessage.asmx")]
        public string Socioboard_Api_FacebookMessage_FacebookMessage {
            get {
                return ((string)(this["Socioboard_Api_FacebookMessage_FacebookMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devapi.socioboard.com/Services/TwitterFeed.asmx")]
        public string Socioboard_Api_TwitterFeed_TwitterFeed {
            get {
                return ((string)(this["Socioboard_Api_TwitterFeed_TwitterFeed"]));
>>>>>>> e052534b7a2a3744cad9dddbc3c6acccf394ca7b
            }
        }
    }
}
